version: '3.7'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB=todol
      POSTGRES_USER=todol_db_user
      POSTGRES_PASSWORD=passw0rd@
      SCHEMA: public
  web:
    build: .
    command: bash -c "sleep 5 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/todol
    ports:
      - "8000:8000"
    depends_on:
      - db


